services:
  server-everything:
    image: ghcr.io/mai0313/mcp-servers:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: prod
    command:
      - npx
      - -y
      - "@modelcontextprotocol/server-everything"
    ports:
      - 6274:6274
      - 6277:6277
    pull_policy: always
    restart: always
