services:
  server-everything:
    image: ghcr.io/mai0313/mcp-servers:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: prod
    command:
      - npx
      - -y
      - "@modelcontextprotocol/server-everything"
    ports:
      - 6274:6274
      - 6277:6277
    pull_policy: always
    restart: always

  playwright-mcp:
    image: mcp/playwright
    command:
      - --port 8930
    ports:
      - 8930:8930
    stdin_open: true
    tty: true
    pull_policy: always
    restart: always

  context7-mcp:
    image: mcp/context7:latest
    ports:
      - 8932:8080
    stdin_open: true
    tty: true
    pull_policy: always
    restart: always
